apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "main-chart.fullname" . }}-environment
  labels:
    {{- include "main-chart.labels" . | nindent 4 }}
data:
  {{- range .Values.environment }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
